/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __PERCEPTEROS_ALL_TYPES_H__
#define __PERCEPTEROS_ALL_TYPES_H__

#include <percepteros/types/type_definitions.h>
#include <percepteros/types/recognition_objects.h>


#endif /* __PERCEPTEROS_ALL_TYPES_H__ */
