/*
 * This file was generated by generate_typesystem.py.
 * Filename:    enclosing_circle
 * Name:        boundingtype
 * Description: No description given
 * Version:     1.0
 * Vendor:      None
 */
#ifndef __ENCLOSING_CIRCLE_H__
#define __ENCLOSING_CIRCLE_H__

#include <rs/feature_structure_proxy.h>
#include <percepteros/types/type_definitions.h>
#include <rs/types/core_types.h>
#include <rs/types/tf_types.h>

namespace percepteros
{

/*
 * EnclosingCircle
 */
class EnclosingCircle : public rs::Annotation
{
private:
  void initFields()
  {
    radius.init(this, "radius");
    height.init(this, "height");
    pose.init(this, "pose");
  }
public:
  // No description given
  rs::FeatureStructureEntry<double> radius;
  // No description given
  rs::FeatureStructureEntry<double> height;
  // No description given
  rs::ComplexFeatureStructureEntry<rs::StampedPose> pose;

  EnclosingCircle(const EnclosingCircle &other) :
      rs::Annotation(other)
  {
    initFields();
  }

  EnclosingCircle(uima::FeatureStructure fs) :
      rs::Annotation(fs)
  {
    initFields();
  }
};

}

TYPE_TRAIT(percepteros::EnclosingCircle, PERCEPTEROS_BOUNDINGTYPE_ENCLOSINGCIRCLE)

#endif /* __ENCLOSING_CIRCLE_H__ */
