/*
 * This file was generated by generate_typesystem.py.
 * Filename:    pipeline_specifications
 * Name:        pipelinetypes
 * Description: No description given
 * Version:     1.0
 * Vendor:      None
 */
#ifndef __PIPELINE_SPECIFICATIONS_H__
#define __PIPELINE_SPECIFICATIONS_H__

#include <rs/feature_structure_proxy.h>
#include <percepteros/types/type_definitions.h>
#include <rs/types/core_types.h>

namespace percepteros
{

/*
 * pipeline identification
 */
class PipelineAnnotation : public rs::Annotation
{
private:
  void initFields()
  {
    pipelineID.init(this, "pipelineID");
  }
public:
  // No description given
  rs::FeatureStructureEntry<std::string> pipelineID;

  PipelineAnnotation(const PipelineAnnotation &other) :
      rs::Annotation(other)
  {
    initFields();
  }

  PipelineAnnotation(uima::FeatureStructure fs) :
      rs::Annotation(fs)
  {
    initFields();
  }
};

}

TYPE_TRAIT(percepteros::PipelineAnnotation, PERCEPTEROS_PIPELINETYPES_PIPELINEANNOTATION)

#endif /* __PIPELINE_SPECIFICATIONS_H__ */
