/*
 * This file was generated by generate_typesystem.py.
 * Filename:    record_data
 * Name:        recorddata
 * Description: No description given
 * Version:     1.0
 * Vendor:      None
 */
#ifndef __RECORD_DATA_H__
#define __RECORD_DATA_H__

#include <rs/feature_structure_proxy.h>
#include <percepteros/types/type_definitions.h>
#include <rs/types/core_types.h>

namespace percepteros
{

/*
 * Record Data
 */
class RecordData : public rs::Identifiable
{
private:
  void initFields()
  {
    record.init(this, "record");
  }
public:
  // No description given
  rs::FeatureStructureEntry<bool> record;

  RecordData(const RecordData &other) :
      rs::Identifiable(other)
  {
    initFields();
  }

  RecordData(uima::FeatureStructure fs) :
      rs::Identifiable(fs)
  {
    initFields();
  }
};

}

TYPE_TRAIT(percepteros::RecordData, PERCEPTEROS_RECORDDATA_RECORDDATA)

#endif /* __RECORD_DATA_H__ */
