/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __PERCEPTEROS_TYPE_DEFINITIONS_H__
#define __PERCEPTEROS_TYPE_DEFINITIONS_H__

#define PERCEPTEROS_RECOGNITIONTYPES_RECOGNITIONOBJECT "percepteros.recognitiontypes.RecognitionObject"

#endif /* __PERCEPTEROS_TYPE_DEFINITIONS_H__ */
