%YAML:1.0
annotators:
    - CollectionReader
    - ImagePreprocessor
    - ObjectRegionFilter
    - NormalEstimator
    - PlaneAnnotator
    - PointCloudColorSegmentation
    - PrimitiveShapeAnnotator
    - PlateAnnotator
    - ROSPublisher
