- regionID: "spatulaRecognition" # valid input can be found in view_names.h
  viewsToProcess: ["cloud"] # appending "_<process_views>" to the name for cas.set
  region_center: [-0.387466371059, 0.170032024384, 0.9]
  range: [0.6, 0.6, 0.6]

- regionID: "plate" # valid input can be found in view_names.h
  viewsToProcess: ["cloud"] # appending "_<process_views>" to the name for cas.set
  region_center: [-0.354085087776, -0.160685777664, 1.2780995369]
  range: [0.4, 0.4, 0.4]

# the correct frame for this would be head_mount_kinect_rgb_optical_frame